/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author DELL
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form MenuAkademik
     */
    public frmMenu() {
        initComponents();
        setSize(1000, 600);
        setLocationRelativeTo(this);
        Koneksi.Database.KoneksiDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        frmNasabah = new javax.swing.JMenuItem();
        frmJenis = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuKeluar = new javax.swing.JMenuItem();
        mnuLaporan = new javax.swing.JMenu();
        mnuDaftarNasabah = new javax.swing.JMenuItem();
        mnuDaftarJenisRekening = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Bank Setiakawan Jakarta");

        mnuFile.setText("File");

        frmNasabah.setText("Nasabah");
        frmNasabah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmNasabahActionPerformed(evt);
            }
        });
        mnuFile.add(frmNasabah);

        frmJenis.setText("Jenis Rekening");
        frmJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmJenisActionPerformed(evt);
            }
        });
        mnuFile.add(frmJenis);
        mnuFile.add(jSeparator3);

        mnuKeluar.setText("Keluar");
        mnuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKeluarActionPerformed(evt);
            }
        });
        mnuFile.add(mnuKeluar);

        jMenuBar1.add(mnuFile);

        mnuLaporan.setText("Laporan");

        mnuDaftarNasabah.setText("Daftar Nasabah");
        mnuDaftarNasabah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDaftarNasabahActionPerformed(evt);
            }
        });
        mnuLaporan.add(mnuDaftarNasabah);

        mnuDaftarJenisRekening.setText("Daftar Jenis Rekening");
        mnuLaporan.add(mnuDaftarJenisRekening);

        jMenuBar1.add(mnuLaporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuDaftarNasabahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDaftarNasabahActionPerformed

    }//GEN-LAST:event_mnuDaftarNasabahActionPerformed

    private void frmNasabahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmNasabahActionPerformed
        // TODO add your handling code here:
        View.FrmNasabah objNsb = new View.FrmNasabah();
        objNsb.setLocationRelativeTo(this);
        objNsb.setVisible(true);
    }//GEN-LAST:event_frmNasabahActionPerformed

    private void frmJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmJenisActionPerformed
        View.FrmJenis objJns= new View.FrmJenis();
        objJns.setLocationRelativeTo(this);
        objJns.setVisible(true);
    }//GEN-LAST:event_frmJenisActionPerformed

   
    private void mnuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem frmJenis;
    private javax.swing.JMenuItem frmNasabah;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem mnuDaftarJenisRekening;
    private javax.swing.JMenuItem mnuDaftarNasabah;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuKeluar;
    private javax.swing.JMenu mnuLaporan;
    // End of variables declaration//GEN-END:variables
}
